apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  namespace: default
spec:
  selector:
    app: ftps
  ports:
    - name: ftp
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv-min
      protocol: TCP
      port: 21009
      targetPort: 21009
    - name: pasv-mid
      protocol: TCP
      port: 21010
      targetPort: 21010
    - name: pasv-max
      protocol: TCP
      port: 21011
      targetPort: 21011
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 20
          name: ftp
        - containerPort: 21
          name: ftps
        - containerPort: 21009
          name: pasv-min
        - containerPort: 21010
          name: pasv-mid
        - containerPort: 21011
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep telegraf && pgrep vsftpd'
          initialDelaySeconds: 10
          periodSeconds: 5
