FROM	alpine:3.12.1

WORKDIR	/usr/share/grafana

RUN		apk add grafana --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache && \
		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache


COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY	/srcs/grafana.db			/usr/share/grafana/data/
COPY	/srcs/start.sh				./

RUN		chmod +x start.sh


EXPOSE	3000

CMD ./start.sh

