FROM	alpine:3.12.1

WORKDIR /var/www

RUN     apk update 					&& \
		apk upgrade 				&& \
		apk add --no-cache nginx 	&& \
		apk add --no-cache openssl	&& \
		apk	add --no-cache openssh

RUN	 	chmod 700 /etc/ssl/private								&& \
		openssl req -x509 -nodes -days 365 -newkey rsa:2048			\
		-subj "/C=SP/ST=Spain/L=Madrid/O=42/CN=127.0.0.1"			\
		-keyout /etc/ssl/private/nginx_server.key 					\
		-out /etc/ssl/certs/nginx_server.crt 					&&	\
		openssl dhparam -out /etc/nginx/dhparam.pem 1000

RUN     adduser -D -g 'www' www				&& \
		mkdir -p /run/nginx /var/www

RUN		chown -R www:www /var/lib/nginx		&& \
		chown -R www:www /var/www

COPY	/srcs/telegraf.conf			./ 
COPY	/srcs/index.html			/var/www/
COPY	/srcs/nginx.conf			/etc/nginx/
COPY	/srcs/start.sh				./

RUN		chmod +x start.sh

RUN 	ssh-keygen -A			&& \
		adduser -D ssh_admin	&& \
		echo "ssh_admin:9090" | chpasswd

RUN		apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community telegraf	&& \
		mkdir -p /etc/telegraf 			&& \
		mv telegraf.conf /etc/telegraf/

EXPOSE	22 80 443

CMD ./start.sh