FROM	alpine:3.12.1

RUN     apk update 					&& \
		apk upgrade 				&& \
		apk add wget nginx php7 php7-fpm php7-mysqli php7-mbstring php7-json php7-session php7-opcache && \
		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

RUN		mkdir -p /usr/share/webapps/ && cd /usr/share/webapps/
RUN		wget https://wordpress.org/wordpress-5.7.tar.gz && tar -xzvf wordpress-5.7.tar.gz && rm wordpress-5.7.tar.gz
RUN		mkdir -p /var/www && mv /wordpress /var/www/

RUN     adduser -D -g 'www' www && \
		mkdir -p /run/nginx www

RUN		chown -R www:www /var/lib/nginx && \
		chown -R www:www /var/www

COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY 	/srcs/nginx.conf			/etc/nginx/nginx.conf
COPY	/srcs/wp-config.php			/var/www/wordpress/
COPY	/srcs/start.sh				./

RUN		chmod +x start.sh

EXPOSE	5050

CMD ./start.sh
